FROM nodered/node-red:latest
USER root
RUN apk add --no-cache \
      sudo \
      curl \
      build-base \
      g++ \
      libpng \
      libpng-dev \
      jpeg-dev \
      pango-dev \
      cairo-dev \
      giflib-dev \
      python \
      ;
